-- Migration: 001_create_alerts.sql
-- Description: Creates the alerts table for CyberShield SOC Incident Prioritization Engine.
-- Database: MySQL 8.0+
-- Conventions:
--   1. All timestamps (timestamp, created_at) are stored in UTC without timezone offset.
--   2. Primary key id defaults to UUID() generated by MySQL.
--   3. CHECK constraints on severity, asset_criticality, data_sensitivity, attack_confidence,
--      and business_impact are enforced in MySQL 8.0+. Application-level validation also enforces
--      these ranges for defensive robustness across database versions.
--   4. related_alert_ids is stored as a JSON column (JSON array of alert_id strings).

CREATE TABLE IF NOT EXISTS alerts (
  id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  alert_id VARCHAR(50) NOT NULL UNIQUE,
  timestamp DATETIME NOT NULL COMMENT 'Event timestamp in UTC',
  alert_type VARCHAR(100) NOT NULL COMMENT 'e.g. failed_login, malware_detection, port_scan, data_exfiltration, suspicious_email, brute_force, privilege_escalation, lateral_movement, suspicious_process',
  severity INT NOT NULL,
  asset VARCHAR(255) NOT NULL COMMENT 'Target hostname / asset name',
  asset_criticality INT NOT NULL,
  data_sensitivity INT NOT NULL,
  attack_confidence INT NOT NULL,
  affected_users INT NOT NULL DEFAULT 0,
  business_impact INT NOT NULL,
  source_ip VARCHAR(45) NOT NULL,
  destination_ip VARCHAR(45) NULL,
  user_account VARCHAR(255) NULL,
  attack_stage ENUM(
    'reconnaissance',
    'initial_access',
    'privilege_escalation',
    'lateral_movement',
    'persistence',
    'exfiltration',
    'none'
  ) NOT NULL,
  mitre_technique VARCHAR(50) NULL,
  ioc_match BOOLEAN NOT NULL DEFAULT FALSE,
  related_alert_ids JSON NULL COMMENT 'JSON array of alert_id strings, e.g. ["ALT-1001", "ALT-1002"]',
  status ENUM('new', 'investigating', 'contained', 'closed') NOT NULL DEFAULT 'new',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record creation time in UTC',

  CONSTRAINT chk_severity CHECK (severity BETWEEN 0 AND 100),
  CONSTRAINT chk_asset_criticality CHECK (asset_criticality BETWEEN 0 AND 100),
  CONSTRAINT chk_data_sensitivity CHECK (data_sensitivity BETWEEN 0 AND 100),
  CONSTRAINT chk_attack_confidence CHECK (attack_confidence BETWEEN 0 AND 100),
  CONSTRAINT chk_business_impact CHECK (business_impact BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

